let players = [
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "34145930",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "34145931",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "34145932",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "34145933",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "341459374",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "34145935",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "34145936",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "34145937",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "34145938",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "34145939",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
  {
    dateBorn: "1990-08-12",
    dateSigned: "2014-08-25",
    idAPIfootball: "1917",
    idPlayer: "341459310",
    idPlayerManager: "43001238",
    idSoccerXML: "725",
    idTeam: "134270",
    idTeam2: "0",
    idTeamNational: null,
    intLoved: "0",
    intSoccerXMLTeamID: "6",
    strAgent: "",
    strBanner: null,
    strBirthLocation: "Palermo, Italy",
    strCollege: null,
    strCreativeCommons: "No",
    strCutout: "https://www.thesportsdb.com/images/media/player/cutout/alfgb41610666098.png",
    strDescriptionCN: null,
    strDescriptionDE: null,
    strDescriptionEN: `Mario Balotelli Barwuah (né Barwuah; born 12 August 1990) is an Italian professional footballer who plays as a striker for Serie B club Monza. He started his professional football career at Lumezzane and played for the first team twice before having an unsuccessful trial at Barcelona, and subsequently joining Inter Milan in 2007. Inter manager Roberto Mancini brought Balotelli into the first team, but when Mancini left, Balotelli's disciplinary record fell away. He had a strained relationship with new manager José Mourinho and was suspended from Inter's first team in January 2009 after a number of disciplinary problems. With doubts over his career at Inter, former coach Roberto Mancini had since moved to Manchester City and decided to give Balotelli a fresh chance at a new club.He joined Manchester City in August 2010, where his performances and off- field activities continued to be enigmatic and unpredictable.Balotelli eventually fell out of favour with Mancini after a \"training ground bust up\" between the two in January 2013. His departure from City and return to Italy with Milan followed several weeks later. After 18 months at Milan, he returned to the Premier League with Liverpool. An unsuccessful season with the Merseyside club led to his return to Milan on loan and subsequent departure on a free transfer to Ligue 1 side Nice. After a spell with fellow French club Marseille in January 2019, he returned to Italy the following summer, joining Brescia, before joining Serie B club Monza in December 2020. Balotelli earned his first cap for Italy in a friendly match against the Ivory Coast on 10 August 2010. He amassed over 30 caps and represented his country at UEFA Euro 2012, the 2013 FIFA Confederations Cup, and the 2014 FIFA World Cup; he helped the national side reach the final of Euro 2012, and also won a bronze medal at the Confederations Cup.Along with Antonio Cassano, he is Italy's top-scorer in the UEFA European Championship with three goals. He is also Italy's top scorer in the FIFA Confederations Cup, alongside Giuseppe Rossi and Daniele De Rossi, with two goals.`,
    strDescriptionES: null,
    strDescriptionFR: null,
    strDescriptionHU: null,
    strDescriptionIL: null,
    strDescriptionIT: null,
    strDescriptionJP: null,
    strDescriptionNL: null,
    strDescriptionNO: null,
    strDescriptionPL: null,
    strDescriptionPT: null,
    strDescriptionRU: null,
    strDescriptionSE: null,
    strFacebook: "www.facebook.com/MarioOfficialBalotelli",
    strFanart1: "https://www.thesportsdb.com/images/media/player/fanart/wwtsqs1431622222.jpg",
    strFanart2: "https://www.thesportsdb.com/images/media/player/fanart/upxsxy1431622235.jpg",
    strFanart3: "https://www.thesportsdb.com/images/media/player/fanart/vxqsyv1431622253.jpg",
    strFanart4: "https://www.thesportsdb.com/images/media/player/fanart/tvxuyq1431622269.jpg",
    strGender: "Male",
    strHeight: "1.89 m (6 ft 2 in)",
    strInstagram: "instagram.com/mb459",
    strKit: "",
    strLocked: "unlocked",
    strNationality: "Italy",
    strNumber: "45",
    strOutfitter: "",
    strPlayer: "Mario Balotelli",
    strPosition: "Forward",
    strRender: null,
    strSide: "",
    strSigning: "",
    strSport: "Soccer",
    strTeam: "Monza",
    strTeam2: "",
    strThumb: "https://www.thesportsdb.com/images/media/player/thumb/qqvuvq1431622719.jpg",
    strTwitter: "twitter.com/finallymario",
    strWage: "",
    strWebsite: "",
    strWeight: "86.17",
    strYoutube: ""
  },
];

export function getPlayers() {
  return players;
}

export function findPlayer(idPlayer) {
  const player = players.find(player => player.idPlayer.toString() === idPlayer.toString());

  return player;
}

export function updatePlayer(newPlayer, idPlayer) {
  let upsertedPlayer;
  players = players.map(player => {
    if (player.idPlayer === idPlayer) {
      player = newPlayer
      upsertedPlayer = player;
    };
    return player;
  });

  return upsertedPlayer;
}

export function createPlayer(newPlayer) {
  players.push(newPlayer);
}

export function removePlayer(idPlayer) {
  console.log(`players.length 1`, players.length);
  players = players.filter(player => player.idPlayer.toString() !== idPlayer.toString());
  console.log(`players.length 2`, players.length);

  return players;
}

export default players;
